// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDsyGevKKPZw-b2IwCInjJnfLiojZTzrw',
    appId: '1:846626737811:web:5c293c1a03881646a50766',
    messagingSenderId: '846626737811',
    projectId: 'kuriftu-1c523',
    authDomain: 'kuriftu-1c523.firebaseapp.com',
    storageBucket: 'kuriftu-1c523.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMwdr-YgN36mLvizWjE1h9vFCmke9QOXg',
    appId: '1:846626737811:android:46076115b200c038a50766',
    messagingSenderId: '846626737811',
    projectId: 'kuriftu-1c523',
    storageBucket: 'kuriftu-1c523.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM1vC5MhfqDVEJpcMnRIsdAoTRRyh4v3w',
    appId: '1:846626737811:ios:9fae85635b23d854a50766',
    messagingSenderId: '846626737811',
    projectId: 'kuriftu-1c523',
    storageBucket: 'kuriftu-1c523.firebasestorage.app',
    iosBundleId: 'com.example.kuriftuHackathon',
  );
}
